{{- if .Values.secrets.enabled }}
{{- range .Values.secrets.opaque }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }} 
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .labelName | default .name }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
type: Opaque
data:
{{- with .data }}
{{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}
